
var permissions_tags = {
    profile: 'public_profile',
    friends: 'user_friends',
    email: 'email',
    about: 'user_about_me',
    books: 'user_actions.books',
    fitnes: 'user_actions.fitness',
    music: 'user_actions.music',
    news: 'user_actions.news',
    video: 'user_actions.video',
    birthday: 'user_birthday',
    education: 'user_education_history',
    events: 'user_events',
    games: 'user_games_activity',
    hometown: 'user_hometown',
    likes: 'user_likes',
    location: 'user_location',
    managed_groups: 'user_managed_groups',
    photos: 'user_photos',
    posts: 'user_posts',
    relationships: 'user_relationships',
    relationship_details: 'user_relationship_details',
    religion: 'user_religion_politics',
    places: 'user_tagged_places',
    videos: 'user_videos',
    website: 'user_website',
    work: 'user_work_history',
    friendlists: 'read_custom_friendlists',
    insights: 'read_insights',
    audience: 'read_audience_network_insights',
    mailboxes: 'read_page_mailboxes',
    pages: 'manage_pages',
    publish_pages: 'publish_pages',
    publish_actions: 'publish_actions',
    event: 'rsvp_event',
    pages_list: 'pages_show_list',
    pages_manage_cta: 'pages_manage_cta',
    pages_manage_instant_articles: 'pages_manage_instant_articles',
    ads_read: 'ads_read',
    ads_management: 'ads_management',
    business_management: 'business_management',
    pages_messaging: 'pages_messaging',
    pages_messaging_phone_number: 'pages_messaging_phone_number'};


var requested_user_field_type_description = [
    'id',
    'numeric string',
    'The id of this persons user account. This ID is unique to each app and cannot be used across different apps. Our upgrade guide provides more information about app-specific IDs',
    'age_range',
    'AgeRange',
    'The age segment for this person expressed as a minimum and maximum age. For example, more than 18, less than 21.',
    'birthday',
    'string',
    'The persons birthday. This is a fixed format string, like MM/DD/YYYY. However, people can control who can see the year they were born separately from the month and day so this string can be only the year (YYYY) or the month + day (MM/DD)',
    'gender',
    'string',
    'The gender selected by this person, male or female. This value will be omitted if the gender is set to a custom value',
    'first_name',
    'string',
    'The persons first name',
    'last_name',
    'string',
    'The persons last name',
    'name',
    'string',
    'The persons full name',
    'email',
    'string',
    'The persons primary email address listed on their profile. This field will not be returned if no valid email address is available',
    'hometown',
    'Page',
    'The persons hometown',
    'locale',
    'string',
    'The persons locale',
    'link',
    'string',
    'A link to the persons Timeline',
     'website',
    'string',
    'The persons website',
    'location',
    'Page',
    'The persons current location as entered by them on their profile. This field is not related to check-ins'
];


var user_fields_type_description = ['id',
    'numeric string',
    'The id of this persons user account. This ID is unique to each app and cannot be used across different apps. Our upgrade guide provides more information about app-specific IDs',
    'about',
    'string',
    'Equivalent to the bio field',
    'age_range',
    'AgeRange',
    'The age segment for this person expressed as a minimum and maximum age. For example, more than 18, less than 21.',
    'bio',
    'string',
    'A short bio, found on a persons profile in the "About This Person" section',
    'birthday',
    'string',
    'The persons birthday. This is a fixed format string, like MM/DD/YYYY. However, people can control who can see the year they were born separately from the month and day so this string can be only the year (YYYY) or the month + day (MM/DD)',
    'context',
    'UserContext',
    'Social context for this person',
    'cover',
    'CoverPhoto',
    'The persons cover photo',
    'currency',
    'Currency',
    'The persons local currency information',
    'devices',
    'list<UserDevice>',
    'The list of devices the person is using. This will return only iOS and Android devices',
    'education',
    'list<EducationExperience>',
    'The persons education',
    'email',
    'string',
    'The persons primary email address listed on their profile. This field will not be returned if no valid email address is available',
    'favorite_athletes',
    'list<Experience>',
    'Athletes the person likes',
    'favorite_teams',
    'list<Experience>',
    'Sports teams the person likes',
    'first_name',
    'string',
    'The persons first name',
    'gender',
    'string',
    'The gender selected by this person, male or female. This value will be omitted if the gender is set to a custom value',
    'hometown',
    'Page',
    'The persons hometown',
    'inspirational_people',
    'list<Experience>',
    'The persons inspirational people',
    'install_type',
    'enum',
    'Install type',
    'installed',
    'bool',
    'Is the app making the request installed?',
    'interested_in',
    'list<string>',
    'Genders the person is interested in',
    'is_shared_login',
    'bool',
    'Is this a shared login (e.g. a gray user)',
    'is_verified',
    'bool',
    'People with large numbers of followers can have the authenticity of their identity manually verified by Facebook. This field indicates whether the persons profile is verified in this way. This is distinct from the verified field',
    'languages',
    'list<Experience>',
    'Facebook Pages representing the languages this person knows',
    'last_name',
    'string',
    'The persons last name',
    'link',
    'string',
    'A link to the persons Timeline',
    'locale',
    'string',
    'The persons locale',
    'location',
    'Page',
    'The persons current location as entered by them on their profile. This field is not related to check-ins',
    'meeting_for',
    'list<string>',
    'What the person is interested in meeting for',
    'middle_name',
    'string',
    'The persons middle name',
    'name',
    'string',
    'The persons full name',
    'name_format',
    'string',
    'The persons name formatted to correctly handle Chinese, Japanese, or Korean ordering',
    'payment_pricepoints',
    'PaymentPricepoints',
    'The persons payment pricepoints',
    'political',
    'string',
    'The persons political views',
    'public_key',
    'string',
    'The persons PGP public key',
    'quotes',
    'string',
    'The persons favorite quotes',
    'relationship_status',
    'string',
    'The persons relationship status',
    'religion',
    'string',
    'The persons religion',
    'security_settings',
    'SecuritySettings',
    'Security settings',
    'shared_login_upgrade_required_by',
    'datetime',
    'The time that the shared loginneeds to be upgraded to Business Manager by',
    'significant_other',
    'User',
    'The persons significant other',
    'sports',
    'list<Experience>',
    'Sports played by the person',
    'test_group',
    'unsigned int32',
    'Platform test group',
    'third_party_id',
    'string',
    'A string containing an anonymous, but unique identifier for the person. You can use this identifier with third parties',
    'timezone',
    'float (min: -24) (max: 24)',
    'The persons current timezone offset from UTC',
    'updated_time',
    'datetime',
    'Updated time',
    'verified',
    'bool',
    'Indicates whether the account has been verified. This is distinct from the is_verified field. Someone is considered verified if they take any of the following actions:',
    'video_upload_limits',
    'VideoUploadLimits',
    'Video upload limits',
    'viewer_can_send_gift',
    'bool',
    'Can the viewer send a gift to this person?',
    'website',
    'string',
    'The persons website',
    'work',
    'list<WorkExperience>',
    'Details of a persons work experience'];
